name: slm-alignment
channels:
  - pytorch
  - nvidia/label/cuda-12.1.1
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - anyio=4.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - binutils=2.38
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - blas=1.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cachecontrol=0.14.0
  - cachecontrol-with-filecache=0.14.0
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cccl=2.3.2
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - cleo=2.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - crashtest=0.4.1
  - cryptography=43.0.0
  - cuda-cccl=12.6.37
  - cuda-cccl_linux-64=12.6.37
  - cuda-command-line-tools=12.1.1
  - cuda-compiler=12.4.1
  - cuda-crt-dev_linux-64=12.6.20
  - cuda-crt-tools=12.6.20
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_linux-64=12.6.37
  - cuda-cudart-static=12.6.37
  - cuda-cudart-static_linux-64=12.6.37
  - cuda-cudart_linux-64=12.6.37
  - cuda-cuobjdump=12.4.127
  - cuda-cupti=12.1.105
  - cuda-cuxxfilt=12.4.127
  - cuda-documentation=12.1.105
  - cuda-driver-dev=12.6.37
  - cuda-driver-dev_linux-64=12.6.37
  - cuda-gdb=12.6.37
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.6.0
  - cuda-libraries-static=12.6.0
  - cuda-nsight=12.6.20
  - cuda-nvcc=12.4.131
  - cuda-nvcc-dev_linux-64=12.6.20
  - cuda-nvcc-impl=12.6.20
  - cuda-nvcc-tools=12.6.20
  - cuda-nvcc_linux-64=12.6.20
  - cuda-nvdisasm=12.6.20
  - cuda-nvml-dev=12.6.37
  - cuda-nvprof=12.6.37
  - cuda-nvprune=12.4.127
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvrtc-static=12.6.20
  - cuda-nvtx=12.1.105
  - cuda-nvvm-dev_linux-64=12.6.20
  - cuda-nvvm-impl=12.6.20
  - cuda-nvvm-tools=12.6.20
  - cuda-nvvp=12.6.37
  - cuda-opencl=12.6.37
  - cuda-opencl-dev=12.6.37
  - cuda-profiler-api=12.6.37
  - cuda-runtime=12.1.0
  - cuda-sanitizer-api=12.6.34
  - cuda-toolkit=12.1.0
  - cuda-tools=12.1.1
  - cuda-version=12.6
  - cuda-visual-tools=12.6.0
  - cycler=0.12.1
  - dbus=1.13.18
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.8
  - dulwich=0.21.7
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gds-tools=1.11.0.15
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jaraco.classes=3.4.0
  - jedi=0.19.1
  - jeepney=0.8.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.11
  - kernel-headers_linux-64=3.10.0
  - keyring=24.3.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcublas-static=12.6.0.22
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufft-static=11.2.6.28
  - libcufile=1.11.0.15
  - libcufile-dev=1.11.0.15
  - libcufile-static=1.11.0.15
  - libcups=2.4.2
  - libcurand=10.3.7.37
  - libcurand-dev=10.3.7.37
  - libcurand-static=10.3.7.37
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusolver-static=11.6.4.38
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libcusparse-static=12.5.2.23
  - libdeflate=1.17
  - libdrm-cos7-x86_64=2.4.97
  - libedit=3.1.20230828
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.78.4
  - libglvnd-cos7-x86_64=1.0.1
  - libglvnd-glx-cos7-x86_64=1.0.1
  - libgomp=14.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnpp-static=12.3.1.23
  - libnvfatbin=12.6.20
  - libnvfatbin-dev=12.6.20
  - libnvfatbin-static=12.6.20
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjitlink-static=12.6.20
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libnvjpeg-static=12.3.3.23
  - libnvvm-samples=12.1.105
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.7.0
  - libxml2=2.13.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mergedeep=1.3.4
  - mesa-khr-devel-cos7-x86_64=18.3.4
  - mesa-libgl-cos7-x86_64=18.3.4
  - mesa-libgl-devel-cos7-x86_64=18.3.4
  - mesa-libglapi-cos7-x86_64=18.3.4
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - more-itertools=10.4.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - mysql=5.7.20
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nbstripout=0.8.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.3
  - notebook-shim=0.2.4
  - nsight-compute=2024.3.0.15
  - nspr=4.35
  - nss=3.89.1
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pkginfo=1.11.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - plotly=5.23.0
  - ply=3.11
  - poetry=1.8.3
  - poetry-core=1.9.0
  - poetry-plugin-export=1.8.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyproject_hooks=1.1.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-build=1.2.1
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-installer=0.7.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.1.0
  - qhull=2020.2
  - qt-main=5.15.2
  - rapidfuzz=3.9.6
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - screeninfo=0.8.1
  - secretstorage=3.3.3
  - send2trash=1.8.3
  - setuptools=72.1.0
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.12
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tenacity=9.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.14
  - tomli=2.0.1
  - tomlkit=0.13.0
  - torchaudio=2.4.0
  - torchinfo=1.8.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - trove-classifiers=2024.7.2
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.2.2
  - virtualenv=20.26.3
  - wayland=1.23.0
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxext=1.3.4
  - xorg-libxinerama=1.1.5
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cudacanvas==1.0.1.post240121
      - fsspec==2024.9.0
      - glfw==2.7.0
      - imageio==2.35.1
      - lazy-loader==0.4
      - line-profiler==4.1.3
      - numpy==2.0.1
      - opencv-python==4.10.0.84
      - pdoc==15.0.0
      - pypylon==4.0.0
      - python-graphviz==0.20.3
      - scikit-image==0.24.0
      - tifffile==2024.9.20
      - torchviz==0.0.2
variables:
  LIB_PATH: /lib/x86_64-linux-gnu/
  INCLUDE_PATH: /usr/include/GLFW
prefix: /home/adminlwe/miniconda3/envs/onn
